CREATE TABLE Addresses(
	Id INT PRIMARY KEY IDENTITY,
	Registration_Date DATETIME NOT NULL,
	Zip_Code VARCHAR(8) NOT NULL,
	Street VARCHAR(50) NOT NULL);

CREATE TABLE Users(
	Id INT PRIMARY KEY IDENTITY,
	Registration_Date DATETIME NOT NULL,
	Email VARCHAR(50) UNIQUE NOT NULL,
	Username VARCHAR(50) UNIQUE NOT NULL,
	Address_Id INT FOREIGN KEY REFERENCES Addresses(Id) UNIQUE NOT NULL);

CREATE TABLE Posts(
	Id INT PRIMARY KEY IDENTITY,
	Registration_Date DATETIME NOT NULL,
	Text VARCHAR(300) NOT NULL,
	User_Id INT FOREIGN KEY REFERENCES Users(Id) NOT NULL
);

CREATE TABLE Likes(
	Id INT PRIMARY KEY IDENTITY,
	Registration_Date DATETIME NOT NULL,
	User_Id INT FOREIGN KEY REFERENCES Users(Id) UNIQUE NOT NULL,
	Post_Id INT FOREIGN KEY REFERENCES Posts(Id) UNIQUE NOT NULL
);

CREATE TABLE Tags(
	Id INT PRIMARY KEY IDENTITY,
	Registration_Date DATETIME NOT NULL,
	Name VARCHAR(50) NOT NULL
);

CREATE TABLE TagsPosts(
	Tag_Id INT FOREIGN KEY REFERENCES Tags(Id) NOT NULL,
	Post_Id INT FOREIGN KEY REFERENCES Posts(Id) NOT NULL
);